import matplotlib.pyplot as plt
from nll import * 

if __name__ == '__main__':

    train_len = 800
    val_len = 200
    test_len = 500
    avgnum = 1
    train_data = None
    with open('data_exp16_train.npy', 'rb') as f:
        train_data = list(np.load(f))
    ############ Training error ##############################33

    # generate true data for a hawkes synthetic process omega=1; mu=0.2; alpha=0.8; history_start=0;
    omega = 1
    np.random.seed(0)
    def predict(mu, alpha, history: History):
        last_time = history.time_slots[-1] + 1e-10
        lambda_max = mu + alpha * \
            np.exp((last_time - history.time_slots) * -1 * omega).sum()
        while (True):
            u = np.random.uniform(0, 1)
            last_time = last_time - (np.log(1-u) / lambda_max)
            u2 = np.random.uniform(0, 1)
            value = (mu + alpha * np.exp((last_time - history.time_slots)
                     * -1 * omega).sum()) / lambda_max
            if u2 <= value:
                break
        return last_time


    train_data = [0]
    mu = 0.2
    alpha = 0.8
    prob_log = 0
    for i in range(1, train_len):
        val = predict(0.2, 0.8, History(train_data[:i]))
        prob_log += np.log(mu + alpha * np.exp((val - History(train_data[:i]).time_slots) * -1 * omega).sum()) - (mu * val) + (alpha/omega * (np.exp(-1 * omega * (val - train_data[-1])) - 1) )
        train_data.append(val)
    print('logprob of actual data (training)', prob_log/train_len)

    temp = train_data.copy()
    val_data = []
    prob_log = 0
    for i in range(val_len):
        val = predict(0.2, 0.8, History(temp))
        prob_log += np.log(mu + alpha * np.exp((val - History(temp).time_slots) * -1 * omega).sum()) - (mu * val) + (alpha/omega * (np.exp(-1 * omega * (val - temp[-1])) - 1) )
        temp.append(val)
        val_data.append(val)
    
    test_data = []
    prob_log = 0
    for i in range(test_len):
        val = predict(0.2, 0.8, History(temp))
        prob_log += np.log(mu + alpha * np.exp((val - History(temp).time_slots) * -1 * omega).sum()) - (mu * val) + (alpha/omega * (np.exp(-1 * omega * (val - temp[-1])) - 1) )
        temp.append(val)
        test_data.append(val)
    print('logprob of actual data (test)', prob_log/test_len)

    assert len(train_data) == train_len
    assert len(val_data) == val_len
    assert len(test_data) == test_len




    # try to get likelihood of actual data when alpha and data are obtained through a non-data minimization of train_len params
    final_T = train_data[-1] + 1e-10
    setting1 = Setting1(None, None, None, final_T, omega, init_num_epochs=300, lr=5e-3, epoch_decay=None, budget=None, sensitivity=None)
    mu, alpha, _ = setting1.do_forward(History(train_data[:(train_len-1)]), None, [train_data[train_len-1]])
    mu = mu.item()
    alpha = alpha.item()
    print('mu', mu, 'alpha', alpha)

    avg = 0
    for j in range(avgnum):
        prob_log = 0
        for i in range(1, train_len):
            prob_log += np.log(mu + alpha * np.exp((train_data[i] - History(train_data[:i]).time_slots) * -1 * omega).sum()) - mu * train_data[i] + alpha/omega * (np.exp(-1 * omega * (train_data[i] - train_data[i-1])) - 1) 
        avg += prob_log/train_len
    print('average logprob of a hawkes process whose parameters are generated by us (training)', avg/avgnum)

    avg = 0
    for j in range(avgnum):
        curr = train_data.copy()
        prob_log = 0
        for i in range(test_len):
            prob_log += np.log(mu + alpha * np.exp((test_data[i] - History(curr).time_slots) * -1 * omega).sum()) - mu * test_data[i] + alpha/omega * (np.exp(-1 * omega * (test_data[i] - curr[-1])) - 1) 
            curr.append(test_data[i])
        avg += prob_log/test_len
    print('average logprob of a hawkes process whose parameters are generated by us (test)', avg/(avgnum))



    # try to get likelihood of actual data when alpha and data are obtained through a data minimization of train_len params
    final_T = val_data[-1] + 1e-10
    setting1 = Setting1(200, 0.6, 1e-3, final_T, omega, init_num_epochs=300, lr=5e-3, epoch_decay=0.6, budget=1.0, sensitivity=None)
    
    # edit 1: We are choosing the initial value in the minimized training data as train_data[0] (it need not be)

    new_history = setting1.greedy_algo(History([]), History(val_data), np.asarray(train_data), False)
    print('new history', new_history.__len__())
    removed_history = np.setdiff1d(train_data, new_history.time_slots)
    plt.scatter(removed_history, np.ones((len(removed_history))), color='r')
    plt.scatter(new_history.time_slots, np.ones((new_history.__len__())), color='b')
    mu, alpha, _ = setting1.do_forward(History(new_history.time_slots[:-1]), None, new_history.time_slots[-1:])
    mu = mu.item()
    alpha = alpha.item()
    print('mu', mu, 'alpha', alpha)

    avg = 0
    for j in range(avgnum):
        curr = list(new_history.time_slots)
        prob_log = 0
        for i in range(test_len):
            prob_log += np.log(mu + alpha * np.exp((test_data[i] - History(curr).time_slots) * -1 * omega).sum()) - mu * test_data[i] + alpha/omega * (np.exp(-1 * omega * (test_data[i] - curr[-1])) - 1) 
            curr.append(test_data[i])
        avg += prob_log/test_len
    print('average logprob of a hawkes process whose parameters are generated by us (minimized) (test)', avg/avgnum)



    # try to get likelihood of actual data when alpha and data are obtained through a data minimization of train_len params with reverse mode
    final_T = val_data[-1] + 1e-10
    setting1 = Setting1(None, 0.6, 1e-3, final_T, omega, init_num_epochs=300, lr=5e-3, epoch_decay=0.6, budget=1.0, sensitivity=None)
    
    new_history = setting1.greedy_algo_with_reverse(History(train_data), History(val_data), False)
    print('new history', new_history.__len__())
    removed_history = np.setdiff1d(train_data, new_history.time_slots)
    plt.scatter(removed_history, np.ones((len(removed_history))), color='r')
    plt.scatter(new_history.time_slots, np.ones((new_history.__len__())), color='b')
    mu, alpha, _ = setting1.do_forward(History(new_history.time_slots[:-1]), None, new_history.time_slots[-1:])
    mu = mu.item()
    alpha = alpha.item()
    print('mu', mu, 'alpha', alpha)

    avg = 0
    for j in range(avgnum):
        curr = list(new_history.time_slots)
        prob_log = 0
        for i in range(test_len):
            prob_log += np.log(mu + alpha * np.exp((test_data[i] - History(curr).time_slots) * -1 * omega).sum()) - mu * test_data[i] + alpha/omega * (np.exp(-1 * omega * (test_data[i] - curr[-1])) - 1) 
            curr.append(test_data[i])
        avg += prob_log/test_len
    print('average logprob of a hawkes process whose parameters are generated by us (minimized) (reverse mode) (test)', avg/avgnum)

    # try to get likelihood of actual data when alpha and data are obtained through a data minimization sensitivity of train_len params
    final_T = train_data[-1] + 1e-10
    setting1 = Setting1(60, 0.6, 1e-3, final_T, omega, init_num_epochs=300, lr=5e-3, epoch_decay=0.6, budget=1.0, sensitivity=None)
    new_history = setting1.greedy_algo(History([train_data[0]]), History(val_data), np.asarray(train_data[1:]), True)
    print('new history', new_history.__len__())
    removed_history = np.setdiff1d(train_data, new_history.time_slots)
    plt.scatter(removed_history, np.ones((len(removed_history))), color='r')
    plt.scatter(new_history.time_slots, np.ones((new_history.__len__())), color='b')
    mu, alpha, _ = setting1.do_forward(History(new_history.time_slots[:-1]), None, new_history.time_slots[-1:])
    mu = mu.item()
    alpha = alpha.item()
    print('mu', mu, 'alpha', alpha)

    avg = 0
    for j in range(avgnum):
        curr = list(new_history.time_slots)
        prob_log = 0
        for i in range(test_len):
            prob_log += np.log(mu + alpha * np.exp((test_data[i] - History(curr).time_slots) * -1 * omega).sum()) - mu * test_data[i] + alpha/omega * (np.exp(-1 * omega * (test_data[i] - curr[-1])) - 1) 
            curr.append(test_data[i])
        avg += prob_log/test_len
    print('average logprob of a hawkes process whose parameters are generated by us (minimized) (sensitiviey) (test)', avg/avgnum)


    # # try to get likelihood of actual data when alpha and data are obtained through a data minimization of train_len params by randomization
    # final_T = train_data[-1] + 1e-10
    # setting1 = Setting1(60, 0.6, 1e-3, final_T, omega, init_num_epochs=300, lr=5e-3, epoch_decay=0.6, budget=1.0, sensitivity=None)
    # new_history = np.random.choice(train_data, int(0.6 * train_len), replace=False)
    # print('new history', new_history.__len__())
    # removed_history = np.setdiff1d(train_data, new_history)
    # plt.scatter(removed_history, 0.2 + np.ones((len(removed_history))), color='r')
    # plt.scatter(new_history, 0.2 + np.ones((len(new_history))), color='b')
    # mu, alpha, _ = setting1.do_forward(History(new_history[:-1]), None, new_history[-1:])
    # mu = mu.item()
    # alpha = alpha.item()
    # print('mu', mu, 'alpha', alpha)

    # avg = 0
    # for j in range(avgnum):
    #     curr = list(new_history)
    #     prob_log = 0
    #     for i in range(test_len):
    #         prob_log += np.log(mu + alpha * np.exp((test_data[i] - History(curr).time_slots) * -1 * omega).sum()) - mu * test_data[i] + alpha/omega * (np.exp(-1 * omega * (test_data[i] - curr[-1])) - 1) 
    #         curr.append(test_data[i])
    #     avg += prob_log/test_len
    # print('average logprob of a hawkes process whose parameters are generated by us (minimized by random) (test)', avg/avgnum)



    # # try to get likelihood of actual data when alpha and data are obtained through a data minimization of train_len params by most recent
    # final_T = train_data[-1] + 1e-10
    # setting1 = Setting1(60, 0.6, 1e-3, final_T, omega, init_num_epochs=300, lr=5e-3, epoch_decay=0.6, budget=1.0, sensitivity=None)
    # new_history = train_data[int(0.4 * train_len):]
    # print('new history', new_history.__len__())
    # removed_history = np.setdiff1d(train_data, new_history)
    # plt.scatter(removed_history, 0.4 + np.ones((len(removed_history))), color='r')
    # plt.scatter(new_history, 0.4 + np.ones((len(new_history))), color='b')
    # mu, alpha, _ = setting1.do_forward(History(new_history[:-1]), None, new_history[-1:])
    # mu = mu.item()
    # alpha = alpha.item()
    # print('mu', mu, 'alpha', alpha)

    # avg = 0
    # for j in range(avgnum):
    #     curr = list(new_history)
    #     prob_log = 0
    #     for i in range(test_len):
    #         prob_log += np.log(mu + alpha * np.exp((test_data[i] - History(curr).time_slots) * -1 * omega).sum()) - mu * test_data[i] + alpha/omega * (np.exp(-1 * omega * (test_data[i] - curr[-1])) - 1) 
    #         curr.append(test_data[i])
    #     avg += prob_log/test_len
    # print('average logprob of a hawkes process whose parameters are generated by us (minimized by recent) (test)', avg/avgnum)

    plt.savefig('time_slot_select.png')