import matplotlib.pyplot as plt
from nll import * 

if __name__ == '__main__':

    train_len = 800
    val_len = 200
    test_len = 500
    lr_data = 1e-2
    num_epochs = 300
    avgnum = 1
    train_data = None
    with open('data_exp16_train.npy', 'rb') as f:
        train_data = list(np.load(f))
    ############ Training error ##############################33

    # generate true data for a hawkes synthetic process omega=1; mu=0.2; alpha=0.8; history_start=0;
    omega = 1
    np.random.seed(0)
    def predict(mu, alpha, history: History):
        last_time = history.time_slots[-1] + 1e-10
        lambda_max = mu + alpha * \
            np.exp((last_time - history.time_slots) * -1 * omega).sum()
        while (True):
            u = np.random.uniform(0, 1)
            last_time = last_time - (np.log(1-u) / lambda_max)
            u2 = np.random.uniform(0, 1)
            value = (mu + alpha * np.exp((last_time - history.time_slots)
                     * -1 * omega).sum()) / lambda_max
            if u2 <= value:
                break
        return last_time

    
    
    def score(histData, mu, alpha, testData):
        # T = None
        T = np.max(testData)
        curr = histData
        prob_log = 0
        for i in range(len(testData)):
            prob_log += np.log(mu + alpha * np.exp((testData[i] - History(curr).time_slots) * -1 * omega).sum()) 
            prob_log += alpha/omega * (np.exp(-1 * omega * (T - testData[i])) - 1)
            curr.append(testData[i])
        if len(histData):
            prob_log -= mu * (np.max(testData) - np.max(histData))
        else:
            prob_log -= mu * T
        return -1 * prob_log/len(testData)


    train_data = [0]
    mu = 0.2
    alpha = 0.8
    for i in range(1, train_len):
        val = predict(0.2, 0.8, History(train_data[:i]))
        train_data.append(val)
    print('logprob of actual data (training)', score([0], mu, alpha, train_data[1:]))

    temp = train_data.copy()
    val_data = []
    for i in range(val_len):
        val = predict(0.2, 0.8, History(temp))
        temp.append(val)
        val_data.append(val)

    test_data = []
    for i in range(test_len):
        val = predict(0.2, 0.8, History(temp))
        temp.append(val)
        test_data.append(val)
    print('logprob of actual data (test)', score(train_data + val_data, mu, alpha, test_data))

    assert len(train_data) == train_len
    assert len(val_data) == val_len
    assert len(test_data) == test_len




    
    



    # try to get likelihood of actual data when alpha and data are obtained through a data minimization of train_len params with reverse mode
    # final_T = train_data[-1] + 1e-10
    final_T = val_data[-1] + 1e-10
    setting1 = Setting1(None, 0.6, 1e-3, final_T, omega, init_num_epochs=num_epochs, lr=lr_data, epoch_decay=1.0, budget=1.0, sensitivity=None)
    
    # new_history = setting1.greedy_algo_with_reverse(History(train_data), None, False)
    new_history = setting1.greedy_algo_with_reverse(History(train_data), History(val_data), False)
    print('new history', new_history.__len__())

    removed_history = np.setdiff1d(train_data, new_history.time_slots)
    plt.scatter(removed_history, 0.2 + np.ones((len(removed_history))), color='r')
    plt.scatter(new_history.time_slots, 0.2+ np.ones((new_history.__len__())), color='b')
    
    mu, alpha, _ = setting1.do_forward(History(new_history.time_slots[:-1]), None, new_history.time_slots[-1:])
    mu = mu.item()
    alpha = alpha.item()
    
    print('mu', mu, 'alpha', alpha)
    print('average logprob of a hawkes process whose parameters are generated by us (minimized) (reverse mode) (test)', score(list(np.concatenate((new_history.time_slots, val_data))), mu, alpha, test_data))

    plt.savefig('time_slot_select_11.png')

    # When random elements are removed each time, the mu and alpha values do not go to (0, 1)
    # The reverse method chooses the elements to be removed such that (mu, alpha) tend to (0, 1)
    # The ones with less mu and high alpha appear to have the maximum likelihood score
    



    # Experiment 1
    # Given the train_data above, we calculate likelihood value 